name: CodeFreeze

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install CodeFreeze
        run: npm install -g moment codefreeze && npm list -g
      - name: Check CodeFreeze Schedule
        run: |
          set -a
          . GITHUB_ENV
          set +a
          node /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/codefreeze/index
